### ISSUE TITLE
Extend custom metrics #17

### ISSUE THREAD

**Issue by kaushiklala** [awaragi/prometheus-mssql-exporter#35]
Hello @awaragi,

Will you be merging or consider merging PR "Extend custom metrics #17" ?

**Comment by awaragi** [comment]
I am debutaing it in my head. On one side, I like custom metrics because every project has different needs. On the other hand, I feel that the exporter will benefit more if people added more metrics. Can you please provide some samples of metrics that are not already exposed that you would have added as custom ones?

**Comment by kaushiklala** [comment]
The idea is to expose business data as metrics, for example if I am
interested in the number of orders per city I can sun the following SELECT
c.City as city, count(*) as order_count_by_city
FROM Dimension.City c, Fact.[Order] o
WHERE c.[City Key] = o.[City Key]
GROUP BY c.City

This will then allow me to monitor the order frequency by city.

**Comment by awaragi** [comment]
If the point is to run arbitrary sql queries then I suggest using the sql exporter instead which is made for generic queries instead of server health and metrics exporter like this one. 

https://github.com/free/sql_exporter

Note there are others but this one pulled 4M+

**Comment by kaushiklala** [comment]
https://github.com/free/sql_exporter does not seem to be maintained, last update was in 2019. But will look at other ones if they meet the requirements.  Thank you @awaragi .
