### ISSUE TITLE
Can I extend the timeout from 15000 to 30000.

### ISSUE THREAD

**Issue by Sujeet1604** [awaragi/prometheus-mssql-exporter#8]
My DB connection is slow because of network. So every request is getting dead after 15000ms. Any help with this.

**Comment by Andysimcoe** [comment]
Are you sure that's actually the problem you have? Does it sometimes connect and other times you have poor network issues causing it to timeout or does it never successfully connect?

I ask because the default error message states it's timing out but if it never connects this may not be the problem. If it's a local instance of MS SQL I would try, for debug purposes, changing 'encrypt: true' to false in index.js and see if you can connect.

**Comment by awaragi** [comment]
I agree with @Andysimcoe . these queries are very fast and should not take more than a fraction of a second to execute.  Exporters should always be as close as possible to their target systems. The exporter can be far from Prometheus.
